#GitHub Actions workflow
name: Java CI with Gradle

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
#Add this step to grant execute permissions to the 'gradlew' script before you attempt to run it.
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v3.1.0


#chmod +x ./gradlew is set to execute permissions : Make Gradle Wrapper Executable
#With this, we can prevent leading to "Permission denied" error.